# version: '3'
# services:
#   web:
#     build: .
#     ports:
#      - "3000:3000"
#     volumes:
#      - .:/nodeapp
#   db:
#     image: mysql
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: "root"
#       MYSQL_DATABASE: "db"

version: '3'
services:
  db:
    image: mysql:5.6.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db"
  web:
    depends_on:
      - db
    build: .
    ports:
     - "3000:3000"
    restart: always
    volumes:
     - .:/nodeapp